### ISSUE TITLE
Could not be compiled. Try rebuilding from source manually.

### ISSUE THREAD

**Issue by WeCantHold** [RemakeAONTeam/AON#1]
因為找不到 Unreal Engine 4.18.2 的選項
所以使用 Unreal Engine 4.18.3 開啟AON.uproject
開啟後顯示:

AON.dll
GitSourceControl.dll
MOBA.dll
MOBA_Editor.dll

因為版本不同需要Rebuild
但Rebuild後顯示

AON Could not be compiled. Try rebuilding from source manually.

顯卡沒有1050以上，但compile 應該跟顯卡無關才對。
想請問4.18.3是否能夠正常建置?

**Comment by explooosion** [comment]
Hi, 出現的問題畫面應該如下吧 ( 踩過坑 😢 ) :

##### MOBA - (這應該是 MOBA 編譯沒成功)
![image](https://user-images.githubusercontent.com/13682994/35183386-206c166e-fe20-11e7-85ca-a8801c509b88.png)

##### GitSourceControl - 可以不用理會, 沒去使用 Git 套件而已
![image](https://user-images.githubusercontent.com/13682994/35183391-2e06acda-fe20-11e7-8299-6b2a9cba9643.png)

##### AON - 整體專案編譯失敗
![image](https://user-images.githubusercontent.com/13682994/35183472-12df7a98-fe22-11e7-96a9-a57987c9c590.png)

---

### 🐞處理步驟

確認看看有無產出 sln 檔案
+ 指令:
```git
git lfs fetch
git lfs pull
```
+ 右鍵 AON.uproject 選擇 Switch ...
![image](https://user-images.githubusercontent.com/13682994/35183403-7f0bf392-fe20-11e7-8195-9da00ea73995.png)

+ 產出sln 專案後再直接點開, 會以 Visual Studio 2017 開啟

+ 開啟後再按下 F5

+ 確認有沒有安裝 [VS 2017 C++ Build Tools](http://landinghub.visualstudio.com/visual-cpp-build-tools)

---

###  🔨 以上都照做還有錯誤的話, 可能是 VS 有遺漏安裝的
參考官方建議安裝步驟 [Setting Up Visual Studio for UE4](https://docs.unrealengine.com/latest/INT/Programming/Development/VisualStudioSetup/)
![image](https://user-images.githubusercontent.com/13682994/35183490-6d16e60e-fe22-11e7-8b8c-b916adced540.png)

---

### ⚠顯示卡問題
顯卡沒有1050以上也是可以跑的，我自己實測 GT640 、GTX750 都可跑
( _雖然最後還是換1060惹 QQ  但真的很順_ )

---

以上建議希望能幫助你 ~ 😊

**Comment by WeCantHold** [comment]
找到問題了   需要安裝window SDK v8.1
![error need win sdk](https://user-images.githubusercontent.com/14094241/35190999-c49d85d0-feaa-11e7-8cb5-3daf54a0a7ed.PNG)

雖然成功開啟AON.uproject
但是沒有找到AON.sln檔案
AON.sln目錄位置跟AON.uproject相同嗎?
